---
abstract: 'Schema-less, versioned media/document database based on Git.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  File::Temp: 0
  Test::Git: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Giddy
requires:
  Any::Moose: 0
  Carp: 0
  Data::Compare: 0
  DateTime::Format::W3CDTF: 0
  Encode: 0
  Fcntl: 0
  File::Path: 0
  File::Spec: 0
  File::Util: 0
  Git::Repository: 0
  Git::Repository::Log::Iterator: 0
  Path::Abstract: 0
  Tie::IxHash: 0
  Try::Tiny: 0
  YAML::XS: 0
  namespace::autoclean: 0
  perl: 5.008
version: 0.01
